id: I1EA74AFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:06:25+00:00'
last_modified: '2022-06-09T06:46:25.913303+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12021
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམིགས་ཁྲིད་གཤེན་བསྟན་གསལ་བའི་སྒྲོན་མེ་དང་འཁྲིད་ཡིག་དམར་མོ་མཛུབ་ཚུག་གི་སྔོན་འགྲོའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A7EA:
      image_group_id: I1KG12030
      title: Volume 1 of byang chub lam gyi rim pa'i dmigs khrid gshen bstan gsal
        ba'i sgron me dang 'khrid yig dmar mo mdzub tshug gi sngon 'gro'i rnam bshad/
      total_pages: 548
      order: 1
      base_file: A7EA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
