id: P007865
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:45:58.493325
source_metadata:
  id: bdr:W1KG12021
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམིགས་ཁྲིད་གཤེན་བསྟན་གསལ་བའི་སྒྲོན་མེ་དང་འཁྲིད་ཡིག་དམར་མོ་མཛུབ་ཚུག་གི་སྔོན་འགྲོའི་རྣམ་བཤད།
  author: ''
  volumes:
    30f9b09c219f4b5eae0406adc2e0d250:
      image_group_id: I1KG12030
      title: Volume 1 of byang chub lam gyi rim pa'i dmigs khrid gshen bstan gsal
        ba'i sgron me dang 'khrid yig dmar mo mdzub tshug gi sngon 'gro'i rnam bshad/
      volume_number: 1
      total_pages: 548
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
