id: opecha:P007865
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12021
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམིགས་ཁྲིད་གཤེན་བསྟན་གསལ་བའི་སྒྲོན་མེ་དང་འཁྲིད་ཡིག་དམར་མོ་མཛུབ་ཚུག་གི་སྔོན་འགྲོའི་རྣམ་བཤད།
  volume: ''
  author: ''
