id: P007865
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12021
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམིགས་ཁྲིད་གཤེན་བསྟན་གསལ་བའི་སྒྲོན་མེ་དང་འཁྲིད་ཡིག་དམར་མོ་མཛུབ་ཚུག་གི་སྔོན་འགྲོའི་རྣམ་བཤད།
  author: ''
  volumes:
    aa21506006aa48be8aba1daf994b645e:
      image_group_id: I1KG12030
      title: ''
      volume_number: 1
      total_pages: 548
ebook_metadata:
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་དམིགས་ཁྲིད་གཤེན་བསྟན་གསལ་བའི་སྒྲོན་མེ་དང་འཁྲིད་ཡིག་དམར་མོ་མཛུབ་ཚུག་གི་སྔོན་འགྲོའི་རྣམ་བཤད།
  author: ''
  sku: P007865
  cover: cover.jpg
  layers:
  - pagination
